version: "3.8"
services: 
    bot:
        container_name: pingBot
        restart: always
        build: .
        env_file: 
            - ./.env
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        env_file: 
            - ./.env
        volumes: 
            - ./data:/data/db
        ports: 
            - "27017:27017"
